version: '3'

services:

  contract:
    build: 
      context: enigma-contract
      dockerfile: Dockerfile.ganache-cli
      args:
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
    ports:
        - "8545:8545"
        - "8081:8081"
        - "8082:8082"
    networks:
        - net 

  surface:
    build: 
      context: surface
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_SURFACE=${GIT_BRANCH_SURFACE}
    depends_on:
      - contract
    stdin_open: true
    tty: true
    volumes:
        - built_contracts:/var/lib/built_contracts
        - ./surface/docker_config.bash:/root/docker_config.bash:ro
    hostname: enigma_surface_${WORKER_INDEX}
    networks:
        - net

  core:
    build:
      context: core
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CORE=${GIT_BRANCH_CORE}
    stdin_open: true
    tty: true
    ports:
      - "5552-5562:5552"
    hostname: enigma_core_${WORKER_INDEX}
    networks:
      - net

networks:
    net:

volumes:
  built_contracts:
