export enum MARKETPLACE_ACTIONS {
  CHANGE_SCHEMA_FILTER = "CHANGE_SCHEMA_FILTER",
  GET_USER_SCHEMAS = "GET_USER_SCHEMAS",
  SCHEMAS_RETRIEVED = "SCHEMAS_RETRIEVED",
  USER_SCHEMAS_RETRIEVED = "USER_SCHEMAS_RETRIEVED",
  GET_ALL_SCHEMAS = "GET_ALL_SCHEMAS"
}

export function updateSchemaFilter(schemaFilter) {
  return {type: MARKETPLACE_ACTIONS.CHANGE_SCHEMA_FILTER, schemaFilter};
}
